### ISSUE TITLE
Masks.values have 20 masks but crash after 8?

### ISSUE THREAD

**Issue by abdullah432** [mtellect/CameraDeepAR#17]
Masks.values.length have 20 values but when i try to `changeMask(9)`, app through exception.

```
E/flutter (10693): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: RangeError (index): Invalid value: Not in inclusive range 0..7: 19
E/flutter (10693): #0      List.[] (dart:core-patch/array.dart:268:52)
E/flutter (10693): #1      CameraDeepArController.changeMask (package:camera_deep_ar/camera_deep_ar.dart:297:50)
E/flutter (10693): #2      _MyAppState.build.<anonymous closure>.<anonymous closure> (package:echata/main.dart:277:54)
E/flutter (10693): #3      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
E/flutter (10693): #4      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:607:11)
E/flutter (10693): #5      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:296:5)
E/flutter (10693): #6      BaseTapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:267:7)
E/flutter (10693): #7      GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:157:27)
E/flutter (10693): #8      GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:443:20)
E/flutter (10693): #9      GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:419:22)
E/flutter (10693): #10     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:287:11)
E/flutter (10693): #11     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:374:7)
E/flutter (10693): #12     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:338:5)
E/flutter (10693): #13     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:296:7)
E/flutter (10693): #14     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:279:7)
E/flutter (10693): #15     _rootRunUnary (dart:async/zone.dart:1370:13)
E/flutter (10693): #16     _CustomZone.runUnary (dart:async/zone.dart:1265:19)
E/flutter (10693): #17     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1170:7)
E/flutter (10693): #18     _invoke1 (dart:ui/hooks.dart:182:10)
E/flutter (10693): #19     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:282:7)
E/flutter (10693): #20     _dispatchPointerDataPacket (dart:ui/hooks.dart:96:31)
```

**Comment by Naveed-dev30** [comment]
Add this line the AR View

supportedMasks: Masks.values,
